insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nunc purus.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', null, 'Vanya', 'Jeanna', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('In sagittis dui vel nisl.', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Green', 'Ruby', 'Robby', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nullam varius.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Turquoise', 'Larina', 'Alysia', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nam tristique tortor eu pede.', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', null, 'Tiler', 'Ronna', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nulla ut erat id mauris vulputate elementum.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Goldenrod', 'Shanna', 'Jo-ann', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Duis mattis egestas metus.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Khaki', 'Arly', 'Dahlia', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Orange', 'Dmitri', 'Chloe', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Mauv', 'Thea', 'Trevor', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Donec quis orci eget orci vehicula condimentum.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Crimson', 'D''arcy', 'Alina', '2022-08-20', '2022-10-11');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nunc nisl.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Teal', 'Saunders', 'Parke', '2022-08-20', '2022-10-11');

insert into user_account (user_id, user_password, nickname, email, memo, created_at, created_by, modified_at, modified_by) values ('abcd123', '1234', 'stranger', 'stranger@mail.com', 'Hello', now(), 'stranger', now(), 'stranger');